# Generated by Django 4.1.7 on 2023-02-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bot_state',
            field=models.CharField(blank=True, help_text='Стейт машина бота', max_length=100, verbose_name='Текущее состояния бота'),
        ),
    ]
