# Generated by Django 4.1.7 on 2023-02-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bot_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bot_state',
            field=models.CharField(blank=True, help_text='Стейт-машина бота', max_length=100, verbose_name='Текущее состояние бота'),
        ),
    ]
