# Generated by Django 4.1.7 on 2023-02-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_bot_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('no status', 'Нет подписки'), ('economy', 'Эконом'), ('base', 'Базовый'), ('vip', 'VIP')], db_index=True, default='no status', max_length=30, verbose_name='Статус'),
        ),
    ]
