# Generated by Django 4.1.7 on 2023-02-14 15:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('telegram_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Telegram Id')),
                ('status', models.CharField(choices=[('not processed', 'Не обработан'), ('Customer', 'Заказчик'), ('Freelancer', 'Фрилансер'), ('Admin', 'Администратор')], db_index=True, default='not processed', max_length=20, verbose_name='Статус')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=100, null=True, verbose_name='Описание заказа')),
                ('status', models.CharField(choices=[('1 not processed', 'Необработан'), ('2 selected', 'Выбран фрилансер'), ('3 performed', 'В работе'), ('4 completed', 'Выполнен'), ('5 expired', 'Просрочен')], db_index=True, default='1 not processed', max_length=30, verbose_name='Статус')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 2, 14, 15, 25, 31, 205297, tzinfo=datetime.timezone.utc), verbose_name='Время создания')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_orders', to=settings.AUTH_USER_MODEL, verbose_name='Фрилансер')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
