# Generated by Django 4.1.7 on 2023-02-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Название заказа'),
        ),
    ]
