# Generated by Django 4.1.7 on 2023-02-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_order_created_at_alter_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
