# Generated by Django 4.1.7 on 2023-02-15 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_order_created_at_alter_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 4, 15, 0, 39512, tzinfo=datetime.timezone.utc), verbose_name='Время создания'),
        ),
    ]
