# Generated by Django 4.1.7 on 2023-02-15 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_profile_user_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 4, 16, 11, 370928, tzinfo=datetime.timezone.utc), verbose_name='Время создания'),
        ),
    ]
