# Generated by Django 4.1.7 on 2023-02-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_order_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('33', 'Необработан'), ('2 selected', 'Выбран фрилансер'), ('3 performed', 'В работе'), ('4 completed', 'Выполнен'), ('5 expired', 'Просрочен')], db_index=True, default='1 not processed', max_length=30, verbose_name='Статус'),
        ),
    ]
