# Generated by Django 4.1.7 on 2023-02-15 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 4, 31, 19, 839654, tzinfo=datetime.timezone.utc), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('not processed', 'Не обработан'), ('Customer', 'Заказчик'), ('Freelancer', 'Фрилансер'), ('Admin', 'Администратор')], db_index=True, default='not processed', max_length=30, verbose_name='Статус'),
        ),
    ]
