# Generated by Django 4.1.7 on 2023-02-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='messages',
            field=models.TextField(blank=True, default='Переписка по заказу "<django.db.models.fields.CharField>"', null=True, verbose_name='Переписка по заказу'),
        ),
    ]
