# Generated by Django 4.1.7 on 2023-02-15 04:37

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_order_created_at_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 4, 37, 49, 26170, tzinfo=datetime.timezone.utc), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region='RU', unique=True, verbose_name='Телефон'),
        ),
    ]
