# Generated by Django 4.1.7 on 2023-02-15 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_order_created_at_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bot_state',
            field=models.CharField(blank=True, help_text='Стейт машина бота', max_length=100, verbose_name='Текущее состояния бота'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 9, 13, 14, 697828, tzinfo=datetime.timezone.utc), verbose_name='Время создания'),
        ),
    ]
