# Generated by Django 4.1.7 on 2023-02-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_order_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='messages',
            field=models.TextField(blank=True, default='Переписка по заказу', null=True, verbose_name='Переписка по заказу'),
        ),
    ]
