# Generated by Django 4.1.7 on 2023-02-15 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_profile_bot_state_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 9, 16, 54, 190129, tzinfo=datetime.timezone.utc), verbose_name='Время создания'),
        ),
    ]
