# Generated by Django 4.1.7 on 2023-02-15 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_order_client_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 12, 56, 48, 238628, tzinfo=datetime.timezone.utc), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание заказа'),
        ),
    ]
