# Generated by Django 4.1.7 on 2023-02-15 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_order_title_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 14, 43, 10, 368647, tzinfo=datetime.timezone.utc), verbose_name='Время создания'),
        ),
    ]
